# This file configures GitHub Pages for your resume site
# The site will be available at: https://sbacht.github.io/Resume/

# GitHub Pages will serve files from the root directory
# Your built site files (from dist/) will be deployed here
